# Stack Sync CLI 配置文件示例
# 支持中英文界面切换

server:
  url: "wss://sync-server.example.com"
  api_key: "your-api-key"

settings:
  # 语言设置：支持 "en-US" (英文) 或 "zh-CN" (中文)
  # 设置为中文后，所有命令和界面都会显示中文
  language: "zh-CN"

  # 备份设置
  backup_enabled: true
  backup_dir: "~/.stack-sync/backups"

  # 界面设置
  show_icons: true
  color_output: true

# 仓库配置列表
repositories:
  - name: "my-backend"
    url: "git@github.com:user/backend.git"
    branch: "main"
    source_directory: "src"
    target_directory: "/Users/aa12/projects/backend/src"
    local_path: "/Users/aa12/projects/backend/src"
    file_patterns:
      - "*.go"
      - "*.mod"
      - "*.sum"
    exclude_patterns:
      - "*.log"
      - "node_modules/"
      - ".git/"
    sync_patterns:
      - "*.go"
      - "*.mod"
      - "*.sum"
    exclude: []
    watch_mode: false
    backup_config:
      enabled: true
      max_backups: 10
    post_sync_commands:
      - directory: "/Users/aa12/projects/backend"
        command: "go mod tidy"
        order: 0
      - directory: "/Users/aa12/projects/backend"
        command: "go build ./..."
        order: 1
    repo_type: "SSH"
    username: ""
    password: ""

  - name: "frontend-app"
    url: "https://github.com/user/frontend.git"
    branch: "develop"
    source_directory: "src/components"
    target_directory: "/Users/aa12/projects/frontend/src/components"
    local_path: "/Users/aa12/projects/frontend/src/components"
    file_patterns:
      - "*.tsx"
      - "*.ts"
      - "*.css"
    exclude_patterns:
      - "*.test.*"
      - "node_modules/"
    sync_patterns:
      - "*.tsx"
      - "*.ts"
      - "*.css"
    exclude: []
    watch_mode: true
    backup_config:
      enabled: true
      max_backups: 5
    post_sync_commands:
      - directory: "/Users/aa12/projects/frontend"
        command: "npm install"
        order: 0
      - directory: "/Users/aa12/projects/frontend"
        command: "npm run build"
        order: 1
    repo_type: "HTTPS"
    username: "your-username"
    password: "your-token"
# 中文命令示例：
#
# 设置 language: "zh-CN" 后，可以使用以下中文命令：
#
# stack-sync 初始化          # 初始化配置
# stack-sync 添加            # 添加仓库
# stack-sync 同步            # 同步所有仓库
# stack-sync 同步 my-backend # 同步指定仓库
# stack-sync 列表            # 列出所有仓库
# stack-sync 状态 my-backend # 查看仓库状态
# stack-sync 删除 my-backend # 删除仓库
# stack-sync 监控            # 启动文件监控
# stack-sync 帮助            # 显示帮助信息
# stack-sync 版本            # 显示版本信息
#
# 所有界面提示和消息也会自动切换为中文
